name: Android UI Tests

on: 
  workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Espresso tests # Runs UI tests using an emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29 # Uses API level 29 emulator
          script: ./gradlew connectedCheck # Runs UI tests

      - name: Upload UI Test Report # Saves UI test reports for review
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-report
          path: app/build/reports/androidTests/connected/
